services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://host.docker.internal:3306/bookStore?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: bibi
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - bookstore-network
    depends_on:
      - frontend

  frontend:
    build:
      context: ./bookstore-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge
